version: "3.7"
services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=football-turf-management
    volumes:
      - db:/var/lib/mysql
    networks: 
     - network-backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/football-turf-management?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    stdin_open: true
    tty: true
    networks: 
     - network-backend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: phanvu26/football-turf-management-web-app
    environment:
      PORT: 4200
      REACT_APP_BASE_URL: http://localhost:8080/api
    ports:
      - "4200:4200"  
    networks: 
     - network-backend

volumes:
  db:

networks:
  network-backend:  
